content:
  - name: posts
    label: Literature (Essays)
    type: collection
    path: content/posts
    view:
      title: title
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: draft
        type: boolean
        default: false
      - name: body
        type: rich-text

  - name: pages
    label: Pages (About & Discord)
    type: collection
    path: content
    view:
      title: title
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text