baseURL = 'https://yumemi.space/'
languageCode = 'en-us'
title = 'Yumemi's Space'
theme = 'PaperMod'

[params.homeInfoParams]
  title = "Yumemi's Space"
  content = "Welcome. A space for literature, thoughts, and quiet reflection."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "Literature"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Discord"
  url = "/discord/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30