baseURL = 'https://yumemi.space/'
languageCode = 'en-us'
title = "Yumemi's Space"
theme = 'PaperMod'

[params]
    images = ["/og-image.png"]

    [params.label]
        text = "Yumemi's Space"
        icon = "/favicon-32x32.png"
        iconHeight = 24

[params.homeInfoParams]
    title = "Hello, stranger. Are you lost too?"
    content = "She who found solace through words. A stray cat hoping to share the warmth to the world."

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 5

[[menu.main]]
    name = "Literature"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "TAGS"
    url = "/tags/"
    weight = 15

[[menu.main]]
    name = "Discord"
    url = "/discord/"
    weight = 20

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[markup.goldmark.renderer]
unsafe = true